version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mining-dashboard-app_web_1
      APP_PORT: 3456

  web:
    image: j1441/mining-dashboard-app:v1.0.0@sha256:<DIGEST_PLACEHOLDER>
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      NODE_ENV: production
      PORT: 3456
      DATA_DIR: /app/data
