version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mining-dashboard-app_web_1
      APP_PORT: 3456

  web:
    image: j73642/mining-dashboard-app:v1.0.1@sha256:45ec3beef7625dcd8929cff9a47050793ba2447389516d6b5092e7757f5f6d7d
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      NODE_ENV: production
      PORT: 3456
      DATA_DIR: /app/data
